### ISSUE TITLE
promisePool

### ISSUE THREAD

**Issue by azole** [hhhhungc/node-workshop#4]
練習了 connection pool 很棒～～

這邊就分享一下，如果 require 的是 "mysql2/promise"，就可以不用特別寫  pool.promise();

例如像這樣:

```javascript
const mysql = require("mysql2/promise");
const pool = mysql.createPool({...});

let [rows] = await pool.query(
      "SELECT * FROM stock WHERE stock_id =?",
      [stockCode]
);
```

兩種寫法都行，單純分享，如果你有什麼想法或是建議，也歡迎跟我分享喔！

**Comment by hhhhungc** [comment]
可以耶 我試了有成功
但還是不太清楚pool是什麼
是不小心嘗試pool，看起來好像成功就推上去XD
謝謝老師!!!!!
